name: 'ESLint (JS/TS) Action with custom node_modules path'
description: 'Lints JavaScript/TypeScript code.'
author: 'lmiguelgato'
branding:
  icon: check-circle
  color: orange
inputs:
  custom-glob:
    description: 'Custom glob to overwrite which files to lint.'
    required: false
    default: 'src'
  custom-path:
    description: 'Custom path where node modules are installed.'
    required: false
    default: ''
runs:
  using: 'node15'
  main: 'dist/index.js'
